language: node_js
node_js:
  - "6"
  - "4"
  
addons:
    code_climate:
        repo_token: fdd38e75529ce5c9f98058cd846159d03c3fa5a358a76b81526670886b92f966

before_script:
  - npm install -g istanbul
  - npm install -g mocha
  - npm install -g codecov
  - npm install -g codeclimate-test-reporter
  
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - codecov
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codeclimate-test-reporter < lcov.info
  